/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/login": {
    post: operations["AuthController_login"];
  };
}

export interface components {
  schemas: {
    AccessTokenResponseDto: {
      access_token: string;
    };
    UnauthorizedResponseDto: {
      /** @default 401 */
      statusCode: number;
      /** @default Unauthorized */
      message: string;
    };
  };
}

export interface operations {
  AuthController_login: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AccessTokenResponseDto"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["UnauthorizedResponseDto"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          username?: string;
          password?: string;
        };
      };
    };
  };
}

export interface external {}
